name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'json'
          filters: |
            terraformRoot:
              - 'terraform'
            terraformSubs:
              - 'terraform/*/'

        # run only if some file in 'src' folder was changed
      - name: echo
        run: |
          echo ${{ steps.changes.outputs.changes }}
          echo ${{ steps.changes.outputs.terraformRoot_files }}
          echo ${{ steps.changes.outputs.terraformSubs_files }}
